<a href="https://colab.research.google.com/github/kaiamj/deep-reinforcement-learning-jumanji/blob/main/ppo_jax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
b = np.array([])
b2 = np.array([2.0,52.0,4.0,7.0])
b = np.append(b,b2)
s =np.vstack([b,b2])

In [18]:
b2 = np.array([2.0,52.0,4.0,7.0])
b3 = jnp.log(b2)

In [13]:
from torch.distributions import Categorical
import torch
p = [2, 50, 90]
dist = Categorical(probs=torch.tensor(p))

# dist = Categorical(torch.tensor([1,23,4,5,2]))
# print("out cat  ",dist )
log_probs = dist.log_prob(torch.tensor([2,5,6]))

ValueError: ignored

In [10]:
import jax
c = jax.random.categorical(key, b2)

In [11]:
for i in s:
  print(i)

[ 2. 52.  4.  7.]
[ 2. 52.  4.  7.]


In [2]:
import jax.numpy as np
from jax import random,vmap

def sum_samples(layer):
    (dw, db) = layer
    (dw, db) = (np.sum(dw, axis=0), np.sum(db, axis=0))
    return np.array([dw, db])

key = random.PRNGKey(1701)
data = random.uniform(key, (10, 2, 20))

result = vmap(sum_samples)(data)
print(result.shape)

(10, 2)


In [35]:
key = random.PRNGKey(1701)
i = jax.random.normal(key,(1,380))

In [46]:
jax.random.categorical(key, logits

DeviceArray([[[9.10784841e-01, 9.00956511e-01, 4.08365369e-01,
               7.35841751e-01, 8.00690055e-01, 5.39383888e-02,
               6.56396985e-01, 4.83418584e-01, 9.21171427e-01,
               8.80449653e-01, 3.09709907e-01, 7.77801037e-01,
               8.92477393e-01, 9.61626410e-01, 9.99255180e-01,
               1.37289643e-01, 6.37572408e-01, 5.11163592e-01,
               4.69839931e-01, 9.16154027e-01],
              [8.52572918e-01, 7.37004638e-01, 1.45462155e-01,
               4.26606178e-01, 8.60655069e-01, 4.40370917e-01,
               4.21858072e-01, 2.93413281e-01, 1.59504175e-01,
               6.33872390e-01, 5.46415687e-01, 6.35575294e-01,
               8.22544098e-06, 7.14041829e-01, 3.95977378e-01,
               5.39646029e-01, 8.98891687e-02, 4.99658227e-01,
               2.09191322e-01, 5.51786423e-02]],

             [[3.44063640e-01, 7.59088278e-01, 8.75769258e-01,
               2.05692530e-01, 7.68872142e-01, 4.85912561e-02,
               3.765

In [34]:
np.append([2],[3],axis = 0)

array([2, 3])

In [28]:
jnp.concatenate([b,b2],axis =1)

ValueError: ignored

In [13]:
c = [2,3 ,4 ]
c.append([3,45])

In [14]:
c

[2, 3, 4, [3, 45]]

In [16]:
!pip install git+https://github.com/instadeepai/jumanji.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/instadeepai/jumanji.git to /tmp/pip-req-build-u0mkr_l_
  Running command git clone --filter=blob:none --quiet https://github.com/instadeepai/jumanji.git /tmp/pip-req-build-u0mkr_l_
  Resolved https://github.com/instadeepai/jumanji.git to commit 10958866909d434ba50edc1915247e4cebc3cb3e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.3/85.3 KB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.3/471.3 KB 17.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 30.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 65.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.4/9.4 MB 75.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1

In [17]:
import numpy as np
import jax
from jax import vmap
import jax.numpy as jnp
import jumanji
from jumanji.wrappers import AutoResetWrapper
import flax.linen as nn

In [20]:

def flatten_jax(obs):
    return jnp.concatenate([obs.ems.x1,obs.ems.x2,
                        obs.ems.y1,obs.ems.y2,
                        obs.ems.z1,obs.ems.z2,
                        obs.ems_mask.flatten(),obs.items.x_len,
                        obs.items.y_len,obs.items.z_len,
                        obs.items_mask.flatten(),obs.items_placed.flatten()])

In [43]:
from flax import linen as nn 
import optax

class SimpleClassifierCompact(nn.Module):
    num_hidden : int   # Number of hidden neurons
    num_outputs : int  # Number of output neurons

    @nn.compact  # Tells Flax to look for defined submodules
    def __call__(self, x):
        # Perform the calculation of the model to determine the prediction
        # while defining necessary layers
        x = nn.Dense(features=self.num_hidden)(x)
        x = nn.tanh(x)
        x = nn.Dense(features=self.num_outputs)(x)
        return x
def critic_calculate_loss( state, V,batch_rtgs):
    #logits = critic_state.apply_fn(params, data).squeeze(axis=-1)
    loss = optax.sigmoid_binary_cross_entropy(V, batch_rtgs).mean()
    print("loss of critic ", loss)
    return loss

@jax.jit  # Jit the function for efficiency
def critic_train_step(state, V,batch_rtgs):
    # Gradient function
    grad_fn = jax.value_and_grad(critic_calculate_loss,  # Function to calculate the loss
                                 argnums=1  # Parameters are second argument of the function
                                 #has_aux=False  # Function has additional outputs, here accuracy
                                )
    # Determine gradients for current model, parameters and batch
    loss, grads = grad_fn(state.params,V,batch_rtgs)
    print("gradient of critic ",grads," type ", type(grads))

    # Perform parameter update with gradients and optimizer
    state = state.apply_gradients(grads=grads)
    # Return state and any other value we might want
    return state
def actor_calculate_loss( state, surr1,surr2):
    #logits = critic_state.apply_fn(params, data).squeeze(axis=-1)
    actor_loss = (-jnp.min(surr1, surr2)).mean()
    print("actor loss ",actor_loss)
    return actor_loss

@jax.jit  # Jit the function for efficiency
def actor_train_step(state,  surr1,surr2):
    # Gradient function
    grad_fn = jax.value_and_grad(actor_calculate_loss,  # Function to calculate the loss
                                 argnums=1  # Parameters are second argument of the function
                                 #has_aux=False  # Function has additional outputs, here accuracy
                                )
    # Determine gradients for current model, parameters and batch
    loss, grads = grad_fn(state.params, surr1,surr2)
    print("gradient of actor ",grads," type ", type(grads))
    # Perform parameter update with gradients and optimizer
    state = state.apply_gradients(grads=grads)
    # Return state and any other value we might want
    return state
#critic_state, loss = critic_train_step(critic_state, data)

In [44]:
lr = 0.1
obs_dim = 380
act_dim = 800

key = jax.random.PRNGKey(0)
key, subkey = jax.random.split(key)
optimizer = optax.sgd(learning_rate=lr)

actor = SimpleClassifierCompact(num_hidden=64, num_outputs=act_dim)
critic = SimpleClassifierCompact(num_hidden=64, num_outputs=1)

params =actor.init(subkey, jnp.arange(obs_dim))
cparams =critic.init(subkey, jnp.arange(obs_dim))
actor_state = train_state.TrainState.create(apply_fn=actor.apply,
                                        params=params,
                                        tx=optimizer)
critic_state = train_state.TrainState.create(apply_fn=critic.apply,
                                        params=cparams,
                                        tx=optimizer)
a = actor_state.apply_fn(actor_state.params, i)

NameError: ignored

In [ ]:
b =critic_state.apply_fn(critic_state.params, i)

In [45]:
b

NameError: ignored

In [48]:
from flax.training import train_state
import pandas as pd
import time


class PPO:
  def __init__(self,env):
    self._init_hyperparameters()
    self.env = env
    
    #initiate actor and critic
    

    self.optimizer = optax.sgd(learning_rate=self.lr)

    self.actor = SimpleClassifierCompact(num_hidden=64, num_outputs=self.act_dim)
    self.critic = SimpleClassifierCompact(num_hidden=64, num_outputs=1)
    
    self.params = self.actor.init(self.subkey, jnp.arange(self.obs_dim))
    self.cparams = self.critic.init(self.subkey, jnp.arange(self.obs_dim))

    self.actor_state = train_state.TrainState.create(apply_fn=self.actor.apply,
                                            params=self.params,
                                            tx=self.optimizer)
    self.critic_state = train_state.TrainState.create(apply_fn=self.critic.apply,
                                            params=self.cparams,
                                            tx=self.optimizer)
     
    
    
    
    
  def _init_hyperparameters(self):
    # Default values for hyperparameters, will need to change later.
    self.timesteps_per_batch = 2  #4800            # timesteps per batch
    #self.max_timesteps_per_episode = 1600      # timesteps per episode
    self.gamma = 0.95
    self.n_updates_per_iteration = 1
    self.clip = 0.2 # As recommended by the paper
    self.lr = 0.1

    self.obs_dim = 380
    self.act_dim = 800

    self.key = jax.random.PRNGKey(0)
    self.key, self.subkey = jax.random.split(self.key)


  def compute_rtgs_jax(self, batch_rews): 
    # The rewards-to-go (rtg) per episode per batch to return.
    # The shape will be (num timesteps per episode)
    
    batch_rtgs = jnp.array([])
    print("batch_rews ",batch_rews)
    # Iterate through each episode backwards to maintain same order in batch_rtgs
    for ep_rews in reversed(batch_rews):
      discounted_reward = 0 # The discounted reward so far
      print(" ep_rews ",ep_rews)
      discounted_reward = ep_rews + discounted_reward * self.gamma
      print("discounted_reward ",discounted_reward)
      batch_rtgs = jnp.insert(batch_rtgs, 0, discounted_reward)
    print("batch_rtgs",batch_rtgs)
    return batch_rtgs


 
  def get_action_jax(self, obs, action_jnp):
    #flatten observation  p = flatten(timestep.observation)
    # inside critic and actor by converting it to np.array(p) by actor you will get action

    #initiate actor and critic
     #actor = FeedForwardNN(380,800)
     logits = self.actor_state.apply_fn(self.actor_state.params, obs)
    
     valid_indices = jnp.nonzero(action_jnp)  # getting valid indicies
     valid_logits = logits[valid_indices]  # getting proper valid action probablities
     valid_logits_array = jnp.reshape(valid_logits, (-1,))  # reshapping it to make it 1D
     index_mapping = [i for i, include in enumerate(action_jnp) if include] # mapping of valid actions on whole set of actions
     # Gumbel's trick
     
     u = jax.random.uniform(self.subkey, shape=valid_logits_array.shape) # generates random uniform values
     
     probs = valid_logits_array - jnp.log(-jnp.log(u)) # logits + random uniform noise
     action = jnp.argmax(probs) # argmax of probs -> action id in filtered array from valid actions
     action_id = index_mapping[action] # action index in the 800 size array from actor output
     log_prob_action = jnp.log(action) # log probability of selected action
     
     return action_id, action, log_prob_action
  
  def rollout(self):
    # batch observations, batch actions, log probs of each action, batch rewards,batch rewards-to-go,episodic lengths in batch
    batch_obs, batch_acts, batch_log_probs, batch_rews, batch_rtgs, batch_lens = jnp.array([]), jnp.array([]), jnp.array([]), jnp.array([]), jnp.array([]),jnp.array([])
    batch_states = []
    step_fn = jax.jit(self.env.step)
    reset_fn = jax.jit(self.env.reset)
    t = 0 
    
    while t < self.timesteps_per_batch: # Number of timesteps run so far this batch
      # Rewards this episode
      ep_rews = jnp.array([])
      
      
      state, timestep = reset_fn(self.key)
      ep_t = 1
      rew = 0.0
      while rew == 0.0:
        batch_states.append(state)
        obs = flatten_jax(timestep.observation)  # Collect observation
        #print("obs  flat ",len(obs))
        if t == 0 and ep_t == 1:
          batch_obs = jnp.append(batch_obs, obs)
        else:
          batch_obs = jnp.vstack([batch_obs, obs])
        #print("batch  ",batch_obs)
        num_ems, num_items = self.env.action_spec().num_values
        action_mask = timestep.observation.action_mask.flatten()
        action_jnp = jnp.array(action_mask, dtype=jnp.float32)

        ems_item_id, action_,log_prob  = self.get_action_jax(obs,action_jnp)
        ems_id, item_id = jnp.divmod(ems_item_id, num_items)

        action = jnp.array([ems_id, item_id])  # Wrap the action as a jax array of shape (2,)
        #batch_states = jnp.append(batch_states, state)

        state,timestep = step_fn(state, action)
        rew = jnp.array(timestep.reward.flatten())[0]
        #print(" rew ", rew," type ", type(rew))
        ep_rews = jnp.append(ep_rews, rew)
        #print(" ep_rews ",ep_rews )
        batch_acts = jnp.append(batch_acts, action_)
        batch_log_probs = jnp.append(batch_log_probs, log_prob)
        ep_t += 1 # Increment timesteps ran this batch so far

      t += ep_t
      batch_rews = jnp.append(batch_rews, ep_rews) 
    
    batch_rtgs = self.compute_rtgs_jax(batch_rews)
    return batch_obs, batch_acts,batch_log_probs, batch_rtgs, t ,rew,batch_states

  def learn(self, total_timesteps):
    t_so_far = 0 # Timesteps simulated so far
    episode_reward = jnp.array([])
    while t_so_far < total_timesteps:              # ALG STEP 
      batch_obs, batch_acts, batch_log_probs, batch_rtgs, t, rew,batch_states = self.rollout()
      # print("len  of batch obs and obs of episode itself",len(batch_obs),batch_obs)
      # print("batch_ act ", batch_acts)
      # print("batch_log_prob ",batch_log_probs)
      # print("batch_rtg ", batch_rtgs)
      
      episode_reward = jnp.append(episode_reward, rew)
      t_so_far += t # Calculate how many timesteps we collected this batch   
      V, _ = self.evaluate(batch_obs, batch_acts)
      A_k = batch_rtgs - V # ALG STEP 5 Calculate advantage
      A_k = (A_k - A_k.mean()) / (A_k.std() + 1e-10) # Normalize advantages
      for i in range(self.n_updates_per_iteration):
        V, curr_log_probs = self.evaluate(batch_obs, batch_acts)
        ratios = jax.lax.exp(curr_log_probs - batch_log_probs)   # Calculate ratios
        surr1 = ratios * A_k  # Calculate surrogate losses
        surr2 = jax.lax.clamp( 1 - self.clip, ratios, 1 + self.clip) * A_k
        print(surr1,surr2,"  surrrrrr  ","  ratios ",ratios, " ak ",A_k)
        
        self.actor_state = actor_train_step(self.actor_state, surr1, surr2)
        self.critic_state = critic_train_step(self.critic_state, V, batch_rtgs)
        
        
    return batch_states, episode_reward
    
  def evaluate(self, batch_obs,batch_acts):
    # Query critic network for a value V for each obs in batch_obs.
    #V = self.critic(batch_obs).squeeze()
#vmap(sum_samples)(data)
    #V = vmap(self.critic_state.apply_fn)(self.critic_state.params, batch_obs)#.squeeze(axis=-1)
    V = jnp.array([])
    #batch_logits = jnp.array([])
    for i in batch_obs:
      
      # print("len of actor param ", len(self.actor_state.params),self.actor_state.params)

      #batch_logits = jnp.append(batch_logits,self.actor_state.apply_fn(self.actor_state.params, i))
      # print("len of out actor ",len(outa), outa )
      # print("critic param ",len(self.critic_state.params),self.critic_state.params)
      # print("obs ", len(i))
      V = jnp.append(V,self.critic_state.apply_fn(self.critic_state.params, i))
    #print("Value func ", V)
    #print("batch_logits ",batch_logits)
    # Calculate the log probabilities of batch actions using most 
    # recent actor network.  # This segment of code is similar to that in get_action()
    #batch_logits = self.actor_state.apply_fn(self.actor_state.params, batch_obs).squeeze(axis=-1)
    # rescaling 
    #log_softmax_probs = jax.nn.log_softmax(batch_logits)
    # print("log_softmax_probs len ",type(log_softmax_probs),log_softmax_probs)
    # print("batch_ actions ", type(batch_acts),batch_acts)
    log_probs = jnp.log(batch_acts)

    return V, log_probs  # Return predicted values V and log probs log_probs
 
  

In [49]:

env = jumanji.make("BinPack-toy-v0")
model = PPO(env)
#batch_obs, batch_acts, batch_log_probs, batch_rtgs, t, rew = model.rollout()
  
%time batch_states, episode_rewards = model.learn(1)
#### with jit env , reset one episode 
# CPU times: user 7.4 s, sys: 103 ms, total: 7.5 s
# Wall time: 7.1 s

/usr/local/lib/python3.8/dist-packages/jax/_src/ops/scatter.py:87: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=float32 to dtype=int32. In future JAX releases this will result in an error.
  warnings.warn("scatter inputs have incompatible types: cannot safely cast "
/usr/local/lib/python3.8/dist-packages/jax/_src/ops/scatter.py:87: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=float32 to dtype=int32. In future JAX releases this will result in an error.
  warnings.warn("scatter inputs have incompatible types: cannot safely cast "
/usr/local/lib/python3.8/dist-packages/jax/_src/ops/scatter.py:87: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=float32 to dtype=int32. In future JAX releases this will result in an error.
  warnings.warn("scatter inputs have incompatible types: cannot safely cast "
/usr/local/lib/python3.8/dist-packages/jax/_src/ops/scatter.p

batch_rews  [0.        0.        0.        0.        0.        0.        0.
 0.        0.        0.        0.        0.        0.        0.6203638]
 ep_rews  0.6203638
discounted_reward  0.6203638
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
 ep_rews  0.0
discounted_reward  0.0
batch_rtgs [0.        0.        0.        0.        0.        0.        0.
 0.        0.        0.        0.        0.        0.        0.6203638]
[ 0.92711484  1.1275     -0.8375287   1.3411393   0.29414117 -0.17339565
 -0.51581496 -0.6962916   0.15005463 -0.8802864  -0.6120951  -2.0183198
         nan         nan] [ 0.

ConcretizationTypeError: ignored